name: Integration Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      platform:
        description: 'PLATFORM'
        type: choice
        required: true
        options:
          - Chrome
          - Firefox
          - Restful
          - iOS
          - iOSSimulator
      tags:
        description: 'Tag_to_execute'
        type: string

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Set up Firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: latest

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest # Optional: Install ChromeDriver

      - name: Cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Tests
        run: |
          mvn test -DPLATFORM=${{ inputs.platform }} -Dcucumber.filter.tags=${{ inputs.tags }}

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: reports/
  deploy-reports:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: integration-test
    steps:
     - name: "Checkout Repository"
       uses: actions/checkout@v3
     - name: "Download Extent report"
       uses: actions/download-artifact@v4
       with:
         name: extent
         path: gh_pages
     - name: "Setup Pages"
       uses: actions/configure-pages@v2
     - name: "Upload Page Artifact"
       uses: actions/upolad-pages-artifact@v1
       with:
         path: gh_pages
     - name: "Deploy to Github pages"
       id: deployment
       uses: actions/deploy-pages@v1
