name: Integration Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      platform:
        description: 'PLATFORM'
        type: choice
        required: true
        options:
          - Chrome
          - Firefox
          - Restful
          - iOS
          - iOSSimulator
      tags:
        description: 'Tag_to_execute'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Set up Firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: latest

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest # Optional: Install ChromeDriver

      - name: Cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Firefox (official PPA)
        run: |
          sudo add-apt-repository -y ppa:mozillateam/ppa
          sudo apt update
          sudo apt install -y firefox
          sudo ln -s /usr/bin/firefox /usr/local/bin/firefox

      - name: Install geckodriver
        run: |
          GECKO_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | grep "tag_name" | cut -d '"' -f 4)
          wget "https://github.com/mozilla/geckodriver/releases/download/$GECKO_VERSION/geckodriver-$GECKO_VERSION-linux64.tar.gz"
          tar -xzf "geckodriver-$GECKO_VERSION-linux64.tar.gz"
          chmod +x geckodriver
          sudo mv geckodriver /usr/local/bin/    

      #      - name: Install Chrome
      #        run: |
      #          sudo apt-get update
      #          sudo apt-get install -y google-chrome-stable
      #
      #      - name: Install Firefox
      #        run: |
      #          sudo add-apt-repository -y ppa:mozillateam/ppa
      #          sudo apt update
      #          sudo apt install -y firefox
      #          sudo ln -s /usr/bin/firefox /usr/local/bin/firefox
      #
      #      - name: Install geckodriver
      #        run: |
      #          GECKO_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | grep "tag_name" | cut -d '"' -f 4)
      #          wget "https://github.com/mozilla/geckodriver/releases/download/$GECKO_VERSION/geckodriver-$GECKO_VERSION-linux64.tar.gz"
      #          tar -xzf "geckodriver-$GECKO_VERSION-linux64.tar.gz"
      #          chmod +x geckodriver
      #          sudo mv geckodriver /usr/local/bin/

      - name: Run Tests
        run: |
          mvn test -DPLATFORM=${{ inputs.platform }} -Dcucumber.filter.tags=${{ inputs.tags }}

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/